version: "3.8"
services:
  postgres-db:
    container_name: parts-unlimited
    image: "postgres" # use latest official postgres version
    restart: always
    environment:
      POSTGRES_DB: asi-allocation
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"