#spring:
#  profiles:
#    active: local
#  datasource:
#    url: jdbc:postgresql://localhost:5433/postgres
#    username: user
#    password: pass
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  flyway:
#    locations: classpath:/db/migration
#    out-of-order: true